/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SubTelas;

import Controller.DAO.CrawlerJpaController;
import Controller.DAO.TesteJpaController;
import Crawler.Model.Webpage;
import Model.Entity.SubUsuario;
import Model.Entity.Testes.Teste;
import Model.Entity.Usuario;
import View.SubTelas.Listagem.telaMapaCrawler;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;

/**
 *
 * @author q216-12
 */
public abstract class telaCrawler extends javax.swing.JInternalFrame {

    public abstract EntityManager getEntityManager();
    private final EntityManager em;
    private Usuario user;
    private SubUsuario sub;

    public telaCrawler(Usuario user) {
        this.user = user;
        this.em = getEntityManager();
        initComponents();
    }

    public telaCrawler(SubUsuario sub) {
        this.sub = sub;
        this.em = getEntityManager();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edtUrl = new javax.swing.JTextField();
        btmIniciar = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        setClosable(true);
        setIconifiable(true);
        setTitle("Crawler");

        btmIniciar.setText("Iniciar");
        btmIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmIniciarActionPerformed(evt);
            }
        });

        jProgressBar1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtUrl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmIniciar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(edtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btmIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmIniciarActionPerformed
        new Thread() {
            @Override
            public void run() {
                Date dt_inicio = new Date();

                Crawler.Controller.Crawler crawler = new Crawler.Controller.Crawler(edtUrl.getText()) {
                    @Override
                    public EntityManager getEntityManager() {
                        return em;
                    }
                };

                Crawler.Model.Dominio DOM = crawler.Play();

                CrawlerJpaController JPA = new CrawlerJpaController(getEntityManager().getEntityManagerFactory());
                TesteJpaController tjpa = new TesteJpaController(getEntityManager().getEntityManagerFactory());

                Model.Entity.Testes.Crawler c = new Model.Entity.Testes.Crawler();
                c.setHoraInicio(dt_inicio);
                c.setHoraFim(new Date());
                c.setIdDominio(DOM);
                if (sub != null) {
                    c.setIdSubUsuario(sub);
                    c.setIdUsuario(sub.getIdUsuario());
                } else {
                    c.setIdUsuario(user);
                }

                //---------------------
                
                JPA.create(c);
                
                Teste teste = new Teste();
                teste.setIdCrawler(c);
                tjpa.create(teste);

                //---------------------
                
                JOptionPane.showMessageDialog(null, "O crawler foi finalizado!");

                List<Crawler.Model.Webpage> resultList = (List<Crawler.Model.Webpage>) em.createNamedQuery("Webpage.findAllByDominio")
                        .setParameter("dominio", DOM)
                        .getResultList();
                List<String> ls = new ArrayList<>();

                for (Webpage rs : resultList) {
                    ls.add(rs.getUrl());
                }

                telaMapaCrawler tela = new telaMapaCrawler(ls, DOM.getDominio());

                tela.setVisible(true);
                getParent().add(tela);
                dispose();
            }
        }.start();
    }//GEN-LAST:event_btmIniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmIniciar;
    private javax.swing.JTextField edtUrl;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
