/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.SubTelas.Listagem;

import Crawler.Model.Webpage;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;

/**
 *
 * @author Matheus
 */
public abstract class TelaCrawler_listagem extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCrawlerExecutados
     */
    public TelaCrawler_listagem() {
        initComponents();
    }

    public abstract EntityManager getEntityManager();

    public abstract Query getQueryLista();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        crawlerQuery = getQueryLista();
        crawlerList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(crawlerQuery.getResultList());
        EntityManager = getEntityManager();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCrawler = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, crawlerList, tblCrawler);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idSubUsuario}"));
        columnBinding.setColumnName("Id Sub Usuario");
        columnBinding.setColumnClass(Model.Entity.SubUsuario.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idUsuario}"));
        columnBinding.setColumnName("Id Usuario");
        columnBinding.setColumnClass(Model.Entity.Usuario.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idDominio}"));
        columnBinding.setColumnName("Id Dominio");
        columnBinding.setColumnClass(Crawler.Model.Dominio.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${horaInicio}"));
        columnBinding.setColumnName("Hora Inicio");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        tblCrawler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCrawlerMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCrawler);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCrawlerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCrawlerMousePressed
        if (evt.getClickCount() == 1) {

            Model.Entity.Testes.Crawler c = crawlerList.get(tblCrawler.getSelectedRow());

            if (c.getWordlist() == null) {

                List<Crawler.Model.Webpage> resultList = (List<Crawler.Model.Webpage>) EntityManager.createNamedQuery("Webpage.findAllByDominio")
                        .setParameter("dominio", c.getIdDominio())
                        .getResultList();
                List<String> ls = new ArrayList<>();

                for (Webpage rs : resultList) {
                    ls.add(rs.getUrl());
                }

                telaMapaCrawler tela = new telaMapaCrawler(ls, c.getIdDominio().getDominio());

                tela.setVisible(true);
                this.getParent().add(tela);
            } else {
                List<Crawler.Model.Webpage> resultList = (List<Crawler.Model.Webpage>) EntityManager.createNamedQuery("Webpage.findAllByDominio")
                        .setParameter("dominio", c.getIdDominio())
                        .getResultList();
                List<String> lf = new ArrayList<>();
                List<String> ld = new ArrayList<>();

                for (Webpage rs : resultList) {
                    if (rs.getIsDirectory()) {
                        ld.add(rs.getUrl());
                    } else {
                        lf.add(rs.getUrl());
                    }
                }

                telaMapaCrawler tela = new telaMapaCrawler(ld, lf, c.getIdDominio().getDominio());

                tela.setVisible(true);
                this.getParent().add(tela);
            }
        }
    }//GEN-LAST:event_tblCrawlerMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager EntityManager;
    private java.util.List<Model.Entity.Testes.Crawler> crawlerList;
    private javax.persistence.Query crawlerQuery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCrawler;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
