/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Cadastro;

import Controller.DAO.SubUsuarioJpaController;
import Controller.DAO.exceptions.NonexistentEntityException;
import Controller.Validações;
import Model.Entity.Permissao;
import Model.Entity.SubUsuario;
import Model.Entity.Usuario;
import View.SubTelas.Listagem.TelaCrawler_listagem;
import java.awt.Color;
import javax.persistence.EntityManager;
import javax.persistence.Query;

/**
 *
 * @author Matheus
 */
public abstract class TelaSubUsuario extends javax.swing.JInternalFrame {

    private Usuario user = null;

    private boolean valEmail = false;

    private boolean valCpf = false;

    private Validações valid;

    public abstract EntityManager getEntityManager();

    /**
     * Creates new form TelaSubUsuario
     */
    public TelaSubUsuario(Usuario user) {
        this.user = user;

        this.valid = new Validações() {
            @Override
            public EntityManager getEntityManager() {
                return EntityManager;
            }
        };

        initComponents();

//        subUsuarioQuery = EntityManager.createNamedQuery("SubUsuario.findAllUser")
//                .setParameter("user", this.user);
//        subUsuarioList.clear();
//        subUsuarioList.addAll(subUsuarioQuery.getResultList());
//
//        permissaoQuery = EntityManager.createNamedQuery("Permissao.findAllUser")
//                .setParameter("user", this.user);
//        permissaoList.clear();
//        permissaoList.addAll(permissaoQuery.getResultList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        EntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("persistencePU").createEntityManager();
        permissaoQuery = EntityManager.createNamedQuery("Permissao.findAllUser")
        .setParameter("user", this.user);
        permissaoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(permissaoQuery.getResultList());
        subUsuarioQuery = EntityManager.createNamedQuery("SubUsuario.findAllUser")
        .setParameter("user", this.user);
        subUsuarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(subUsuarioQuery.getResultList());
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtBusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSubUsuario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        edtCpf = new javax.swing.JFormattedTextField();
        edtNomeCompleto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        btmCriarPermissao = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JPanel();
        btmSalvar1 = new javax.swing.JLabel();
        boxPermissao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        btmCancelar1 = new javax.swing.JLabel();
        edtChave = new javax.swing.JTextField();
        btnNovo = new javax.swing.JPanel();
        btmNovo1 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        btmEditar1 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JPanel();
        btmExcluir1 = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Gerenciar Sub-Usuarios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Buscar");

        edtBusca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtBusca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtBusca.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));
        edtBusca.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                edtBuscaCaretUpdate(evt);
            }
        });
        edtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtBuscaActionPerformed(evt);
            }
        });

        tblSubUsuario.setRowHeight(25);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, subUsuarioList, tblSubUsuario);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tblSubUsuario);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        edtCpf.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));
        try {
            edtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblSubUsuario, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cpf}"), edtCpf, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        edtCpf.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                edtCpfCaretUpdate(evt);
            }
        });

        edtNomeCompleto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtNomeCompleto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblSubUsuario, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomeCompleto}"), edtNomeCompleto, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        edtNomeCompleto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                edtNomeCompletoCaretUpdate(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/icons8-customer.png"))); // NOI18N
        jLabel6.setText("Nome completo");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/cadastro/icons8-credit-card (1).png"))); // NOI18N
        jLabel7.setText("CPF");

        edtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblSubUsuario, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.email}"), edtEmail, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        edtEmail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                edtEmailCaretUpdate(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Email");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/icons8-customer.png"))); // NOI18N
        jLabel9.setText("Nome");

        edtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edtNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 102, 102)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblSubUsuario, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), edtNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        edtNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                edtNomeCaretUpdate(evt);
            }
        });

        btmCriarPermissao.setText("Criar Permissão");
        btmCriarPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCriarPermissaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Permissao");

        btnSalvar.setBackground(new java.awt.Color(52, 152, 219));

        btmSalvar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btmSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btmSalvar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/cadastro/icons8-checkmark (2).png"))); // NOI18N
        btmSalvar1.setText("Salvar");
        btmSalvar1.setEnabled(false);
        btmSalvar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btmSalvar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btmSalvar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btmSalvar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnSalvarLayout = new javax.swing.GroupLayout(btnSalvar);
        btnSalvar.setLayout(btnSalvarLayout);
        btnSalvarLayout.setHorizontalGroup(
            btnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmSalvar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnSalvarLayout.setVerticalGroup(
            btnSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmSalvar1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, permissaoList, boxPermissao);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblSubUsuario, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idPermissao}"), boxPermissao, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        boxPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPermissaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Chave");

        btnCancelar.setBackground(new java.awt.Color(52, 152, 219));

        btmCancelar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btmCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btmCancelar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/cadastro/icons8-delete (1).png"))); // NOI18N
        btmCancelar1.setText("Cancelar");
        btmCancelar1.setEnabled(false);
        btmCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btmCancelar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btmCancelar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btmCancelar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        edtChave.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblSubUsuario, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.senha}"), edtChave, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btnNovo.setBackground(new java.awt.Color(52, 152, 219));

        btmNovo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btmNovo1.setForeground(new java.awt.Color(255, 255, 255));
        btmNovo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/cadastro/icons8-add-file.png"))); // NOI18N
        btmNovo1.setText("Novo");
        btmNovo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btmNovo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btmNovo1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btmNovo1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnNovoLayout = new javax.swing.GroupLayout(btnNovo);
        btnNovo.setLayout(btnNovoLayout);
        btnNovoLayout.setHorizontalGroup(
            btnNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNovoLayout.setVerticalGroup(
            btnNovoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmNovo1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnEditar.setBackground(new java.awt.Color(52, 152, 219));

        btmEditar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btmEditar1.setForeground(new java.awt.Color(255, 255, 255));
        btmEditar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/cadastro/icons8-edit.png"))); // NOI18N
        btmEditar1.setText("Editar");
        btmEditar1.setEnabled(false);
        btmEditar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btmEditar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btmEditar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btmEditar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmEditar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmEditar1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        btnExcluir.setBackground(new java.awt.Color(52, 152, 219));

        btmExcluir1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btmExcluir1.setForeground(new java.awt.Color(255, 255, 255));
        btmExcluir1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmExcluir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icones/cadastro/icons8-delete.png"))); // NOI18N
        btmExcluir1.setText("Excluir");
        btmExcluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btmExcluir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btmExcluir1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btmExcluir1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnExcluirLayout = new javax.swing.GroupLayout(btnExcluir);
        btnExcluir.setLayout(btnExcluirLayout);
        btnExcluirLayout.setHorizontalGroup(
            btnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmExcluir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnExcluirLayout.setVerticalGroup(
            btnExcluirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmExcluir1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtEmail)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtNomeCompleto)
                    .addComponent(edtCpf))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtChave, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(boxPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmCriarPermissao)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btmCriarPermissao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        edtId.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblSubUsuario, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.id}"), edtId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        edtId.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(edtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validacaoGeral() {
        if (tblSubUsuario.getRowCount() > 0) {
            validarCpf();
            validarEmail();
            validarNome();
            validarNomeCompleto();
            if (valEmail && valCpf
                    && edtNome.getBackground().equals(Color.green)
                    && edtNomeCompleto.getBackground().equals(Color.green)
                    && boxPermissao.getSelectedItem() != null) {

                return true;

            }
        } else {
            edtNome.setBackground(null);
            edtCpf.setBackground(null);
            edtEmail.setBackground(null);
//            edtChave.setBackground(null);
            edtNomeCompleto.setBackground(null);
        }
        return false;
    }

    private void validarEmail() {

        valEmail = valid.validarEmail(edtEmail.getText());
        if (valEmail == false) {
            edtEmail.setBackground(Color.red);
        } else {
            edtEmail.setBackground(Color.green);
        }
    }

    private void validarCpf() {
        if (estadoSubUsuario == estadoSubUsuario.INSERINDO_SUB_USUARIO) {

            valCpf = valid.validarCpf(user, edtCpf.getText());
            if (valCpf == false) {
                edtCpf.setBackground(Color.red);
            } else {
                edtCpf.setBackground(Color.green);
            }

        } else if (tblSubUsuario.getRowCount() > 0) {
            valCpf = valid.validarCpf(user, edtCpf.getText(), subUsuarioList.get(tblSubUsuario.getSelectedRow()));
            if (valCpf == false) {
                edtCpf.setBackground(Color.red);
            } else {
                edtCpf.setBackground(Color.green);
            }
        }
    }

    private void validarNome() {
        if (edtNome.getText().length() < 2) {
            edtNome.setBackground(Color.red);
        } else {
            edtNome.setBackground(Color.green);
        }
    }

    private void validarNomeCompleto() {
        if (edtNomeCompleto.getText().length() < 5 && !edtNomeCompleto.getText().contains(" ")) {
            edtNomeCompleto.setBackground(Color.red);
        } else {
            edtNomeCompleto.setBackground(Color.green);
        }
    }

    private void edtBuscaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_edtBuscaCaretUpdate
        if (!edtBusca.getText().isEmpty()) {
            subUsuarioQuery = EntityManager.createNamedQuery("SubUsuario.findByNomeLikeUser")
                    .setParameter("user", user)
                    .setParameter("nome", "%" + edtBusca.getText() + "%");
        } else {
            subUsuarioQuery = EntityManager.createNamedQuery("SubUsuario.findAllUser")
                    .setParameter("user", user);
        }
        subUsuarioList.clear();
        subUsuarioList.addAll(subUsuarioQuery.getResultList());

        if (tblSubUsuario.getRowCount() > 0) {
            tblSubUsuario.setRowSelectionInterval(0, 0);
        } else {
            edtNome.setText(null);
//            edtChave.setText(null);
            edtCpf.setText(null);
            edtEmail.setText(null);
            edtNomeCompleto.setText(null);
            boxPermissao.setSelectedItem(null);
            //-----------------------------------
            edtNome.setBackground(null);
            edtCpf.setBackground(null);
            edtEmail.setBackground(null);
//            edtChave.setBackground(null);
            edtNomeCompleto.setBackground(null);

        }

        configurarParaConsulta();

    }//GEN-LAST:event_edtBuscaCaretUpdate

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        configuraInicializacao();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btmCriarPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCriarPermissaoActionPerformed
        TelaPermissoes telaPermissoes = new TelaPermissoes(user) {
            @Override
            public EntityManager getEntityManager() {
                return EntityManager;
            }
        };
        telaPermissoes.setVisible(true);
        this.getParent().add(telaPermissoes);
    }//GEN-LAST:event_btmCriarPermissaoActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        permissaoQuery = EntityManager.createNamedQuery("Permissao.findAllUser")
                .setParameter("user", user);
        permissaoList.clear();
        permissaoList.addAll(permissaoQuery.getResultList());
    }//GEN-LAST:event_formInternalFrameActivated

    private void edtNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_edtNomeCaretUpdate
        validarNome();
    }//GEN-LAST:event_edtNomeCaretUpdate

    private void edtNomeCompletoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_edtNomeCompletoCaretUpdate
        validarNomeCompleto();
    }//GEN-LAST:event_edtNomeCompletoCaretUpdate

    private void edtCpfCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_edtCpfCaretUpdate
        validarCpf();
    }//GEN-LAST:event_edtCpfCaretUpdate

    private void edtEmailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_edtEmailCaretUpdate
        validarEmail();
    }//GEN-LAST:event_edtEmailCaretUpdate

    private void edtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtBuscaActionPerformed

    private void boxPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPermissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxPermissaoActionPerformed

    private void btmNovo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmNovo1MouseEntered
        btnNovo.setBackground(new java.awt.Color(41, 128, 185));
    }//GEN-LAST:event_btmNovo1MouseEntered

    private void btmNovo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmNovo1MouseExited
        btnNovo.setBackground(new java.awt.Color(52, 152, 219));
    }//GEN-LAST:event_btmNovo1MouseExited

    private void btmNovo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmNovo1MousePressed
        inserirSubUsuario();
    }//GEN-LAST:event_btmNovo1MousePressed

    private void btmEditar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmEditar1MouseEntered
        btnEditar.setBackground(new java.awt.Color(41, 128, 185));
    }//GEN-LAST:event_btmEditar1MouseEntered

    private void btmEditar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmEditar1MouseExited
        btnEditar.setBackground(new java.awt.Color(52, 152, 219));
    }//GEN-LAST:event_btmEditar1MouseExited

    private void btmEditar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmEditar1MousePressed
        configurarParaEdicao();
    }//GEN-LAST:event_btmEditar1MousePressed

    private void btmExcluir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmExcluir1MouseEntered
        btnExcluir.setBackground(new java.awt.Color(41, 128, 185));
    }//GEN-LAST:event_btmExcluir1MouseEntered

    private void btmExcluir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmExcluir1MouseExited
        btnExcluir.setBackground(new java.awt.Color(52, 152, 219));
    }//GEN-LAST:event_btmExcluir1MouseExited

    private void btmExcluir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmExcluir1MousePressed
        try {
            SubUsuarioJpaController JPA = new SubUsuarioJpaController(EntityManager.getEntityManagerFactory());
            JPA.destroy(Integer.parseInt(edtId.getText()));

            int linhaSelecionada = tblSubUsuario.getSelectedRow();
            subUsuarioList.remove(tblSubUsuario.getSelectedRow());
            if (tblSubUsuario.getRowCount() > 0) {
                if (linhaSelecionada > 0) {
                    linhaSelecionada--;
                }
                tblSubUsuario.setRowSelectionInterval(linhaSelecionada, linhaSelecionada);
            }

        } catch (NonexistentEntityException | NumberFormatException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btmExcluir1MousePressed

    private void btmSalvar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmSalvar1MouseEntered
        btnSalvar.setBackground(new java.awt.Color(41, 128, 185));
    }//GEN-LAST:event_btmSalvar1MouseEntered

    private void btmSalvar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmSalvar1MouseExited
        btnSalvar.setBackground(new java.awt.Color(52, 152, 219));
    }//GEN-LAST:event_btmSalvar1MouseExited

    private void btmSalvar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmSalvar1MousePressed
        try {

            if (this.estadoSubUsuario == EstadoSubUsuario.INSERINDO_SUB_USUARIO) {
                salvarSubUsuario_Insersao();
            } else {
                salvarSubUsuario_Atualizacao();
            }

//            subUsuarioQuery = EntityManager.createNamedQuery("SubUsuario.findAllUser")
//                    .setParameter("user", this.user);
//            subUsuarioList.clear();
//            subUsuarioList.addAll(subUsuarioQuery.getResultList());
//
//            permissaoQuery = EntityManager.createNamedQuery("Permissao.findAllUser")
//                    .setParameter("user", this.user);
//            permissaoList.clear();
//            permissaoList.addAll(permissaoQuery.getResultList());
//            
//            tblSubUsuario.revalidate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btmSalvar1MousePressed

    private void btmCancelar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmCancelar1MouseEntered
        btnCancelar.setBackground(new java.awt.Color(41, 128, 185));
    }//GEN-LAST:event_btmCancelar1MouseEntered

    private void btmCancelar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmCancelar1MouseExited
        btnCancelar.setBackground(new java.awt.Color(52, 152, 219));
    }//GEN-LAST:event_btmCancelar1MouseExited

    private void btmCancelar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmCancelar1MousePressed
        try {
            if (estadoSubUsuario == estadoSubUsuario.INSERINDO_SUB_USUARIO) {
                cancelarInsercaoSubUsuario();
            } else {
                cancelarAtualizacaoSubUsuario();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btmCancelar1MousePressed

    private enum EstadoSubUsuario {
        INSERINDO_SUB_USUARIO,
        EDITANDO_SUB_USUARIO,
        CONSULTANDO_SUB_USUARIO
    }

    private EstadoSubUsuario estadoSubUsuario = EstadoSubUsuario.CONSULTANDO_SUB_USUARIO;

    private void configuraInicializacao() {

        if (tblSubUsuario.getRowCount() > 0) {
            tblSubUsuario.setRowSelectionInterval(0, 0);
        }

        configurarParaConsulta();
    }

    private void configurarParaConsulta() {
        btnNovo.setEnabled(true);
        btnExcluir.setEnabled(tblSubUsuario.getRowCount() != 0);
        btnEditar.setEnabled(tblSubUsuario.getRowCount() != 0);
        btmCriarPermissao.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);

        estadoSubUsuario = EstadoSubUsuario.CONSULTANDO_SUB_USUARIO;
        estadoCampos(false);
    }

    private void configurarParaEdicao() {
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
        btmCriarPermissao.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);

        if (estadoSubUsuario == EstadoSubUsuario.CONSULTANDO_SUB_USUARIO) {
            if (tblSubUsuario.getRowCount() != 0) {
                estadoSubUsuario = EstadoSubUsuario.EDITANDO_SUB_USUARIO;
                estadoCampos(true);
            }
        }
    }

    private void configurarParaInsersao() {
        btnNovo.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
        btmCriarPermissao.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);

        estadoSubUsuario = EstadoSubUsuario.INSERINDO_SUB_USUARIO;
        estadoCampos(true);
    }

    private void salvarSubUsuario_Insersao() {
        if (validacaoGeral()) {
            SubUsuarioJpaController JPA = new SubUsuarioJpaController(EntityManager.getEntityManagerFactory());
            SubUsuario sub = new SubUsuario();

            try {

                sub = preencherSubUsuario(sub);
                JPA.create(sub);

                subUsuarioList.remove(tblSubUsuario.getSelectedRow());

                subUsuarioList.add(sub);

                tblSubUsuario.setRowSelectionInterval(tblSubUsuario.getRowCount() - 1,
                        tblSubUsuario.getRowCount() - 1);

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                configurarParaConsulta();
            }
        }
    }

    private String getHash(String s) {
//        MessageDigest m;
//        try {
//            m = MessageDigest.getInstance("MD5");
//            m.update(s.getBytes(), 0, s.length());
//
//            return (new BigInteger(1, m.digest()).toString(16));
//
//        } catch (NoSuchAlgorithmException ex) {
//            ex.printStackTrace();
//        }
//
//        return null;
        String hash = "";
        char[] array_char = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'x', 'w', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'X', 'W', 'Y', 'Z', '1', '2', '3', '4', '5', '6', '7', '8', '9'};

        for (int i = 0; i < 6; i++) {
            hash += array_char[(int) (Math.random() * (array_char.length - 1))];
        }

        if (hash.equalsIgnoreCase(user.getSenha())) {
            hash = getHash("");
        }
        return hash;
    }

    private SubUsuario preencherSubUsuario(SubUsuario sub) {
        sub.setNome(edtNome.getText());
        sub.setEmail(edtEmail.getText());
        sub.setNomeCompleto(edtNomeCompleto.getText());
        sub.setCpf(edtCpf.getText());

        sub.setIdPermissao((Permissao) boxPermissao.getSelectedItem());
        sub.setIdUsuario(user);

//        sub.setHash(getHash(String.valueOf(sub.hashCode())
//                + String.valueOf(user.hashCode())
//                + String.valueOf(boxPermissao.getSelectedItem().hashCode())));
//        sub.setHash(edtChave.getText());
        sub.setSenha(getHash(""));
        return sub;
    }

    private void estadoCampos(boolean e) {
        edtNome.setEnabled(e);
        edtCpf.setEnabled(e);
        edtEmail.setEnabled(e);
        //edtChave.setEnabled(e);
        edtNomeCompleto.setEnabled(e);
        boxPermissao.setEnabled(e);
    }

    private void salvarSubUsuario_Atualizacao() {
        if (validacaoGeral()) {
            SubUsuarioJpaController JPA = new SubUsuarioJpaController(EntityManager.getEntityManagerFactory());
            SubUsuario sub = JPA.findSubUsuario(Integer.parseInt(edtId.getText()));

            try {

                sub = preencherSubUsuario(sub);
                JPA.edit(sub);

            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                configurarParaConsulta();
            }
        }
    }

    private void inserirSubUsuario() {
        SubUsuario sub = new SubUsuario();
        this.subUsuarioList.add(sub);

        tblSubUsuario.setRowSelectionInterval(tblSubUsuario.getRowCount() - 1,
                tblSubUsuario.getRowCount() - 1);
        edtBusca.requestFocus();

        configurarParaInsersao();
    }

    private void cancelarInsercaoSubUsuario() {

        subUsuarioList.remove(tblSubUsuario.getSelectedRow());

        if (tblSubUsuario.getRowCount() > 0) {
            tblSubUsuario.setRowSelectionInterval(tblSubUsuario.getRowCount() - 1,
                    tblSubUsuario.getRowCount() - 1);
        }

        configurarParaConsulta();

    }

    private void cancelarAtualizacaoSubUsuario() {
        SubUsuarioJpaController JPA = new SubUsuarioJpaController(EntityManager.getEntityManagerFactory());
        SubUsuario sub = JPA.findSubUsuario(Integer.parseInt(edtId.getText()));

        edtNome.setText(sub.getNome());
        edtChave.setText(sub.getSenha());
        edtCpf.setText(sub.getCpf());
        edtEmail.setText(sub.getEmail());
        edtNomeCompleto.setText(sub.getNomeCompleto());
        boxPermissao.setSelectedItem(sub.getIdPermissao());

        configurarParaConsulta();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager EntityManager;
    private javax.swing.JComboBox<Model.Entity.Permissao> boxPermissao;
    private javax.swing.JLabel btmCancelar1;
    private javax.swing.JButton btmCriarPermissao;
    private javax.swing.JLabel btmEditar1;
    private javax.swing.JLabel btmExcluir1;
    private javax.swing.JLabel btmNovo1;
    private javax.swing.JLabel btmSalvar1;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnExcluir;
    private javax.swing.JPanel btnNovo;
    private javax.swing.JPanel btnSalvar;
    private javax.swing.JTextField edtBusca;
    private javax.swing.JTextField edtChave;
    private javax.swing.JFormattedTextField edtCpf;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtId;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtNomeCompleto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private java.util.List<Model.Entity.Permissao> permissaoList;
    private javax.persistence.Query permissaoQuery;
    private java.util.List<Model.Entity.SubUsuario> subUsuarioList;
    private javax.persistence.Query subUsuarioQuery;
    private javax.swing.JTable tblSubUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
